export enum ConstraintTypes {
  AJOUT_FORMATION,
  AJOUT_MODULE,
  AJOUT_PERIODE,
  EN_MEME_TEMPS_QUE,
  PAS_EN_MEME_TEMPS_QUE,
  DISPENSE_PERIODE,
  DISPENSE_MODULE,
  A_PARTIR_DE_MODELE,
  LIEUX,
  HEURES_MIN,
  HEURES_MAX
}
