export enum ConstraintTypes {
  AJOUT_FORMATION = "AJOUT_FORMATION",
  AJOUT_MODULE = "AJOUT_MODULE",
  AJOUT_PERIODE = "AJOUT_PERIODE",
  EN_MEME_TEMPS_QUE = "EN_MEME_TEMPS_QUE",
  PAS_EN_MEME_TEMPS_QUE = "PAS_EN_MEME_TEMPS_QUE",
  DISPENSE_PERIODE = "DISPENSE_PERIODE",
  DISPENSE_MODULE = "DISPENSE_MODULE",
  A_PARTIR_DE_MODELE = "A_PARTIR_DE_MODELE",
  LIEUX = "LIEUX",
  HEURES_MIN = "HEURES_MIN",
  HEURES_MAX = "HEURES_MAX"
}
